# @package agent.encoder

type_to_select: vector

pixel:
  type: pixel
  feature_dim: ${agent.encoder_feature_dim}
  num_filters: ${agent.num_filters}
  num_layers: ${agent.num_layers}

vector:
  type: feedforward
  feature_dim: ${agent.encoder_feature_dim}
  num_layers: ${agent.num_layers}
