# @package _group_
name: dmcontrol-walker-skill-distribution-v0
num_envs: 23
builder:
  _target_: mtrl.env.builder.build_dmcontrol_vec_env
  domain_name: walker_skill
  task_name: walk
  prefix: skill
  make_kwargs:
    frame_skip: 4 # same as action_repeat, choose frame_skip=4 as before
    visualize_reward: False
    from_pixels: False
    seed: ${setup.seed}
train:
  - 2
eval:
  # interpolation: ${env.train}
  # extrapolation: ${env.train}
  base: ${env.train}
description:
  