# @package _group_
# skill_list
# 0 "forward_walker/vel_1",
# 1 "forward_walker/vel_2",
# 2 "forward_walker/vel_3",
# 3 "forward_walker/vel_4",
# 4 "forward_walker/vel_5",
# 5 "forward_walker/vel_6",
# 6 "forward_walker/vel_7",
# 7 "forward_walker/vel_8",
# 8 "backward_walker/vel_1",
# 9 "backward_walker/vel_2",
# 10  "backward_walker/vel_3",
# 11  "backward_walker/vel_4",
# 12  "backward_walker/vel_5",
# 13  "backward_walker/vel_6",
# 14  "backward_walker/vel_7",
# 15  "backward_walker/vel_8",
# 16  "high_knee_run_walker/slow",
# 17  "high_knee_run_walker/vel_1",
# 18  "crawl_walker/vel_1",
# 19  "crawl_walker/vel_2",
# 20  "crawl_walker/vel_3",
# 21  "crawl_walker/vel_4",
# 22  "crawl_walker/vel_5",
# 23  "crawl_walker/vel_6",
# 24  "jump_walker/vel_3",
# 25  "jump_walker/vel_4",
# 26  "jump_walker/vel_5",
# 27  "jump_walker/vel_6",
# 28  "jump_walker2/vel_1",
# 29  "jump_walker2/vel_2",
# 30  "jump_walker2/vel_3",
# 31  "jump_walker2/vel_4",
# 32  "jump_walker2/vel_5",
# 33  "jump_walker2/vel_6",
name: dmcontrol-walker-skill-distribution-v0
num_envs: 34
builder:
  _target_: mtrl.env.builder.build_dmcontrol_vec_env
  domain_name: walker_skill
  task_name: walk
  prefix: skill
  make_kwargs:
    frame_skip: 1 # same as action_repeat, choose frame_skip=4 as before
    visualize_reward: False
    from_pixels: False
    seed: ${setup.seed}
train:
  - 24
eval:
  # interpolation: ${env.train}
  # extrapolation: ${env.train}
  base: ${env.train}
description:
  